### ISSUE TITLE
Relicense under the MIT license

### ISSUE THREAD

**Issue by zrax** [zrax/string_theory#1]
string_theory was originally ported out of the `plString` and `plFormat` classes and associated tests from the [H-uru/Plasma](https://github.com/H-uru/Plasma) project.  Since H-uru/Plasma is licensed under the GPLv3, and since string_theory is therefore considered a derivative work under the terms of the GPL, this means that string_theory exists today also under the GPLv3 license.

In order to allow greater flexibility in the use of string_theory by other applications and libraries, I would like to relicense string_theory under a more permissive license.  The MIT license allows for maximum reuse by being compatible with a large variety of open- and closed-source software and licenses, while still maintaining the copyright and license for derivatives and end users.

This proposal is for the immediate relicensing of string_theory to the MIT license. For more information about the license terms, please see [https://en.wikipedia.org/wiki/MIT_License](https://en.wikipedia.org/wiki/MIT_License). In order to go ahead with this proposal, we need permission from everyone who has contributed to the included code to relicense their code under the new terms.  The complete list includes:
- Bartek Bok @boq
- Darryl Pogue @dpogue
- Adam Johnson @Hoikas
- Anne Marije van der Meer @Lunanne
- Michael Hansen @zrax (myself)

Please respond below with a statement clearly indicating if you will allow your code to be relicensed under the MIT license.

**Comment by zrax** [comment]
I hereby give permission for my contributions to be relicensed under the MIT license.

**Comment by Hoikas** [comment]
I agree to allow my code to be relicensed under the MIT license.

**Comment by dpogue** [comment]
I hereby give permission for my contributions to be relicensed under the
MIT license.

**Comment by Lunanne** [comment]
I hereby give permission to relicense my contributions under the MIT license.

**Comment by boq** [comment]
I hereby give permission to relicense my contributions under the MIT
license.
