### ISSUE TITLE
ST::format() fails tests on Solaris 10/GCC 5.5

### ISSUE THREAD

**Issue by tallpgr** [zrax/string_theory#13]
Attempting to build string_theory on Solaris 10 using GCC 5.5.

First tests on format.decimal fail with:

```
[ RUN      ] format.decimal
FanCode/H-uru/string_theory/test/test_format.cpp:173: Failure
      Expected: ST::string::from_literal("" "xx127xx" "", sizeof("xx127xx") - 1)
      Which is: ST::string{"xx127xx"}
To be equal to: ST::format("xx{}xx", std::numeric_limits<int8_t>::max())
      Which is: ST::string{"xxx"}
FanCode/H-uru/string_theory/test/test_format.cpp:174: Failure
      Expected: ST::string::from_literal("" "xx+127xx" "", sizeof("xx+127xx") - 1)
      Which is: ST::string{"xx+127xx"}
To be equal to: ST::format("xx{+}xx", std::numeric_limits<int8_t>::max())
      Which is: ST::string{"xxx"}
FanCode/H-uru/string_theory/test/test_format.cpp:175: Failure
      Expected: ST::string::from_literal("" "xx-128xx" "", sizeof("xx-128xx") - 1)
      Which is: ST::string{"xx-128xx"}
To be equal to: ST::format("xx{}xx", std::numeric_limits<int8_t>::min())
      Which is: ST::string{"xxï¿½xx"}
FanCode/H-uru/string_theory/test/test_format.cpp:176: Failure
      Expected: ST::string::from_literal("" "xx-128xx" "", sizeof("xx-128xx") - 1)
      Which is: ST::string{"xx-128xx"}
To be equal to: ST::format("xx{+}xx", std::numeric_limits<int8_t>::min())
      Which is: ST::string{"xxï¿½xx"}
[  FAILED  ] format.decimal (0 ms)

=========
Other tests failing:
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] format.decimal
[  FAILED  ] format.hex
[  FAILED  ] format.hex_upper
[  FAILED  ] format.octal
[  FAILED  ] format.binary
```

Will keep this issue updated as debugging progresses.  Insights appreciated.

**Comment by zrax** [comment]
At first glance, it looks like it's calling the `char` formatter rather than the `signed char` one...  I wonder if `int8_t` is typedeffed to `char` on Solaris 10.  Where did you find GCC 5 for Solaris 10?  Or is it something you built yourself from source?

**Comment by tallpgr** [comment]
Indeed Solaris 10 declares `int8_t `as `char` not `signed char`.  This apparently is an artifact of the SVID ABI as a default case for x86/x86_64 architectures, and is ensconced in <`types.h`>.  To indicate this state, the symbol `_CHAR_IS_SIGNED` is predefined by all the compilers as well as <`types.h`>

GCC5 was built from source, as was all of the support code and tools.  Solaris is not a common target for open source projects and pre-built packages are hard to come by.  There are also GCC6 and GCC7 on this host, reasonably up to date, however GCC5 is the default as much of the underlying OS support code was built with that generation of GCC.

I take it that this will mean that special consideration will need to be made under Solaris to redirect usage of the `char ` formatter to the `signed char` formatter?  That can be determined with the preprocessor symbol `__sun__` or `__svr4__` being defined.

**Comment by zrax** [comment]
I'm not sure anything can be done to protect clients of string_theory from within ST itself, at least not without breaking backwards compatibility...  However, the tests can probably be fixed by changing to `numeric_limits<signed char>::...`, which matches the interface of the formatter itself.  If that fixes it, go ahead and send a pull request.

**Comment by tallpgr** [comment]
How will that affect building existing clients such as libHSPlasma on Solaris?  Would they require a similar modification?

**Comment by zrax** [comment]
Yeah, they will if they use the `int8_t` type.  I may consider a breaking change for 3.0, but we'll have to be careful about rolling it out.

**Comment by tallpgr** [comment]
Thanks!
