### ISSUE TITLE
Hex Format Prefix Inconsistent

### ISSUE THREAD

**Issue by Hoikas** [zrax/string_theory#17]
When using the `{#x}` format specifier, eg `ST::printf(fp, "\t{#x},", *codes++);`, the `0x` prefix will not be applied if the value passed in is `0`. Other values correctly receive the prefix.

**Comment by zrax** [comment]
That is correct.  It does this intentionally to match behavior with C's `printf`:

>   **Flag characters**
>   The character % is followed by zero or more of the following flags:
>
>   `#`  The  value  should  be  converted to an "alternate form".  For o conversions, the first character of the output  string  is  made zero (by prefixing a 0 if it was not zero already).  For x and X conversions, **a nonzero result** has the string "0x" (or "0X" for X conversions)  prepended  to  it. [...]

**Comment by Hoikas** [comment]
I'll update the other project in this case :smile:
